- name: Aftab Shaikh
  location: [Karachi, Pakistan]
  profile_image: [https://dzone.com/users/5158012/aftabmshaikh.html]
  email: [https://www.linkedin.com/in/aftab-shaikh-7130175]
  linkedin: "https://www.linkedin.com/in/aftab-shaikh-7130175"
  current_title: "Sr Consultant & Software Architect"
  current_company: [Consultant]